"""
Bienvenido al día 🎉100🎉 de #100diasdepython        
            El reto de hoy es:
Utiliza try para capturar e imprimir la excepción 
dentro de  la siguiente función y agrega un mensaje 
            final utilizando finally
    En este reto si se aceptan multiples print
"""


def dia100():
    mensaje = "Llegaste al último día"
    print(mensaje[len(mensaje)])


dia100()